In [1]:
%load_ext line_profiler
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import gym
import pathlib
import typing as tp
from scipy.special import softmax
import pandas as pd

In [3]:
sys.path.insert(0, '/mnt/ubuntu_data_hdd/school/masters/uwaterloo/1b/cs885/project/codenames/codenames_ai/src')

In [4]:
from default_game import *
from codenames import *
from codenames_env import *

In [5]:
import scann

In [6]:
glove.vectors.shape

(400000, 300)

In [7]:
# searcher = scann.scann_ops_pybind.builder(glove.vectors, 20, "dot_product").tree(
#     num_leaves=2000, num_leaves_to_search=300, training_sample_size=250000).score_ah(
#     2, anisotropic_quantization_threshold=0.2).reorder(100).build()

In [8]:
def compute_recall(neighbors, true_neighbors):
    total = 0
    for gt_row, row in zip(true_neighbors, neighbors):
        total += np.intersect1d(gt_row, row).shape[0]
    return total / true_neighbors.size

In [6]:
glove.vectorize(["hot dog", "vanilla ice cream"]).shape

(2, 300)

In [76]:
%timeit guesser.generate_word_suggestions_mean_approx(["seal" , "antarctica", "meal"], 20)

458 µs ± 1.12 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [77]:
%timeit guesser.generate_word_suggestions_minimax_approx(["seal" , "antarctica", "meal"], 20)

1.78 ms ± 9.34 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [78]:
%timeit guesser.generate_word_suggestions_minimax(["seal" , "antarctica", "meal"], 20)

15 ms ± 140 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [79]:
%timeit guesser.generate_word_suggestions_mean(["seal" , "antarctica", "meal"], 20)

11.6 ms ± 42.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [73]:
guesser.generate_word_suggestions_minimax(["seal" , "antarctica", "meal"], 20)

(array(['SHEEP', 'FROZEN', 'CRUST', 'WARM', 'TIP', 'PLATE', 'COLD',
        'FOUND', 'WHALE', 'EXCEPT', 'SALMON', 'HERDS', 'ICE', 'BIRDS',
        'HUNTING', 'FISHING', 'PART', 'WATER', 'ANIMALS', 'TUNA'],
       dtype='<U68'),
 array([0.17065495, 0.17747653, 0.16777915, 0.17051882, 0.16651243,
        0.20739967, 0.17263836, 0.16866185, 0.18349618, 0.1663252 ,
        0.17003855, 0.1648033 , 0.16315228, 0.164646  , 0.15517467,
        0.16137823, 0.15814513, 0.16325317, 0.16153371, 0.16132432],
       dtype=float32))

In [61]:
guesser.give_hint_candidates(["seal" , "antarctica"], strategy="approx_mean")

(array(['SEAL', 'ANTARCTICA', 'ANTARCTIC', 'GREENLAND', 'SEALS', 'ARCTIC',
        'POLAR', 'SEA', 'WEDDELL', 'OCEAN'], dtype='<U68'),
 array([0.5548296 , 0.5548296 , 0.48517594, 0.4253925 , 0.42118257,
        0.40078425, 0.37852728, 0.34951   , 0.33835346, 0.3367697 ],
       dtype=float32))

In [52]:
codenames_hacked_env.generate_candidates([], 3)

array(['LITTER', 'TRAIN', 'ROBOT'], dtype='<U11')

In [9]:
codenames_hacked_env = CodenamesEnvHack(glove, wordlist)

In [10]:
codenames_hacked_env.start_new_game()
codenames_hacked_env.render()
type(codenames_hacked_env.current_observation())

[['TRIANGLE_BL' 'BED_RE' 'ROBOT_RE' 'DISEASE_RE' 'SCREEN_BL']
 ['TRAIN_BL' 'FOREST_RE' 'SATURN_BY' 'PASS_BL' 'STREAM_BL']
 ['MISSILE_BY' 'CHAIR_RE' 'RACKET_BL' 'LITTER_BY' 'JET_BY']
 ['LEMON_AS' 'TIME_BY' 'FRANCE_RE' 'HOTEL_RE' 'CAPITAL_BY']
 ['NIGHT_BL' 'KID_BL' 'TRIP_RE' 'DROP_BL' 'FOOT_BY']]
It is BLUE's turn.
The bot is on the BLUE team.
Remaining words: {'ASSASSIN': {'LEMON'}, 'BLUE': {'KID', 'DROP', 'TRIANGLE', 'NIGHT', 'STREAM', 'RACKET', 'PASS', 'TRAIN', 'SCREEN'}, 'BYSTANDER': {'JET', 'FOOT', 'SATURN', 'LITTER', 'CAPITAL', 'MISSILE', 'TIME'}, 'RED': {'ROBOT', 'TRIP', 'FOREST', 'DISEASE', 'CHAIR', 'FRANCE', 'HOTEL', 'BED'}}
Remaining word count: {'ASSASSIN': 1, 'BLUE': 9, 'BYSTANDER': 7, 'RED': 8}
Hint history: []
Guessed words []



numpy.ndarray

In [11]:
def bench_me():
    action = codenames_hacked_env.action_space.sample()
    step = codenames_hacked_env.step(action)
    print(step[1:3])

In [12]:
bench_me()

(-1, False)


In [16]:
qq = np.arange(12).reshape(3, 4)

In [20]:
em = np.arange(100, 244).reshape(12, 12)

In [21]:
em[qq]

array([[[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123],
        [124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147]],

       [[148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171],
        [172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183],
        [184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195]],

       [[196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207],
        [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219],
        [220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231],
        [232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243]]])

In [51]:
glove.vectors[[np.array([0, 1])]] @ glove.vectors[np.array([1, 2, 3])].T

/home/sherman/miniconda3/envs/fn_env/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([[0.5202359 , 0.6081388 , 0.70579576],
       [0.99999994, 0.7548188 , 0.5423798 ]], dtype=float32)

In [55]:
np.min(glove.vectors[[np.array([0, 1])]] @ glove.vectors[np.array([1, 2, 3])].T, axis=1)

/home/sherman/miniconda3/envs/fn_env/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([0.5202359, 0.5423798], dtype=float32)

In [14]:
%lprun -f GloveGuesser.generate_word_suggestions_mean_approx bench_me()

(-1, False)


Timer unit: 1e-06 s

Total time: 0.002149 s
File: /mnt/ubuntu_data_hdd/school/masters/uwaterloo/1b/cs885/project/codenames/codenames_ai/src/codenames.py
Function: generate_word_suggestions_mean_approx at line 430

Line #      Hits         Time  Per Hit   % Time  Line Contents
   430                                               def generate_word_suggestions_mean_approx(self, words: tp.List[str], limit: int = 10) -> tp.Tuple[tp.Sequence[str], tp.Sequence[float]]:
   431         1          6.0      6.0      0.3          assert self.glove.normalized and self.glove.use_approximate
   432         1        558.0    558.0     26.0          word_vector = self.glove.vectorize(words).mean(0)
   433         1       1512.0   1512.0     70.4          chosen_words, similarity_scores = self.glove.searcher.search(word_vector, final_num_neighbors=limit)
   434         1         71.0     71.0      3.3          chosen_words = self.glove.tokens[chosen_words]
   435         1          2.0      2.0      0.1

In [15]:
%lprun -f bench_me bench_me()

(-1, False)


Timer unit: 1e-06 s

Total time: 0.003831 s
File: <ipython-input-11-115d76da6bb3>
Function: bench_me at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents

In [20]:
codenames_hacked_env.render()

[['TRIANGLE_BL' 'bed_re' 'ROBOT_RE' 'DISEASE_RE' 'SCREEN_BL']
 ['TRAIN_BL' 'FOREST_RE' 'SATURN_BY' 'PASS_BL' 'STREAM_BL']
 ['MISSILE_BY' 'CHAIR_RE' 'RACKET_BL' 'LITTER_BY' 'JET_BY']
 ['LEMON_AS' 'time_by' 'FRANCE_RE' 'HOTEL_RE' 'capital_by']
 ['night_bl' 'kid_bl' 'trip_re' 'drop_bl' 'FOOT_BY']]
It is BLUE's turn.
The bot is on the BLUE team.
Remaining words: {'ASSASSIN': {'LEMON'}, 'BLUE': {'TRIANGLE', 'STREAM', 'RACKET', 'PASS', 'TRAIN', 'SCREEN'}, 'BYSTANDER': {'JET', 'FOOT', 'SATURN', 'LITTER', 'MISSILE'}, 'RED': {'ROBOT', 'DISEASE', 'FOREST', 'CHAIR', 'FRANCE', 'HOTEL'}}
Remaining word count: {'ASSASSIN': 1, 'BLUE': 6, 'BYSTANDER': 5, 'RED': 6}
Hint history: [Hint(word='THEN', count=11, team='BLUE', num_guessed=1, num_guessed_correctly=0), Hint(word='WHICH', count=11, team='BLUE', num_guessed=1, num_guessed_correctly=0), Hint(word='JUST', count=17, team='BLUE', num_guessed=4, num_guessed_correctly=3), Hint(word='YOU', count=12, team='BLUE', num_guessed=1, num_guessed_correctly=0)]
